import hudson.tasks.test.AbstractTestResultAction
import java.util.Optional
import hudson.model.Actionable
import hudson.tasks.junit.CaseResult
import groovy.json.*

node {

    stage ("get app")
    {
    checkout scm
    }

    stage ("Compile application") {

       def cwd = pwd()

       sh "docker run -i -v ${cwd}:/tmp -w /tmp romicaraicu/gatling-docker:latest mvn clean compile -Dorg.slf4j.simpleLogger.defaultLogLevel=error -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -DskipTests"
    }

    stage ("Run tests") {
           def cwd = pwd()
        sh "docker run -i -v ${cwd}:/tmp -w /tmp romicaraicu/gatling-docker:latest mvn gatling:test -Dgatling.simulationClass=Simulations.TestSim"

    }

    stage("publish results") {

    }

    stage ("Send stop notification") {
    }
}



def info(String message){
    ansiColor('xterm') {
        echo "\u001b[1m\u001b[36m[ INFO:  ]\u001b[0m " + message
    }
}