import hudson.tasks.test.AbstractTestResultAction
import java.util.Optional
import hudson.model.Actionable
import hudson.tasks.junit.CaseResult
import groovy.json.*

node {
    stage ("Compile application") {
       sh 'docker run -i -v "$(pwd)":/tmp -w "/tmp" romicaraicu/gatling-docker:latest mvn clean install -Dorg.slf4j.simpleLogger.defaultLogLevel=error"'
    }

    stage ("Run tests") {
        sh 'docker run -i -v "$(pwd)":/tmp -w "/tmp" romicaraicu/gatling-docker:latest mvn gatling:test -Dgatling.simulationClass=Simulations.TestSim "'

    }

    stage("publish results") {

    }

    stage ("Send stop notification") {
    }
}



def info(String message){
    ansiColor('xterm') {
        echo "\u001b[1m\u001b[36m[ INFO:  ]\u001b[0m " + message
    }
}