import hudson.tasks.test.AbstractTestResultAction
import java.util.Optional
import hudson.model.Actionable
import hudson.tasks.junit.CaseResult
import groovy.json.*

node {

    stage ("get app")
    {
    checkout scm

    println(getModel)
    println(getParams)
    }

    stage ("Compile application") {

//      def cwd = pwd()
//       String dockerRunCmd = "docker run -i -v ${cwd}:/tmp -w /tmp romicaraicu/gatling-docker:latest mvn clean compile"
//       String mvnArgs = "-Dorg.slf4j.simpleLogger.defaultLogLevel=error -B -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn -DskipTests"
//       String gatlingTest = "gatling:test -Dgatling.simulationClass=Simulations.TestSim"
//       String testParams = ""

//       sh "${dockerRunCmd} ${gatlingTest} ${testParams} ${mvnArgs}"
    }

    stage ("Run tests") {

       // sh "docker run -i -v ${cwd}:/tmp -w /tmp romicaraicu/gatling-docker:latest mvn gatling:test -Dgatling.simulationClass=Simulations.TestSim"

    }

    stage("publish results") {

    }

    stage ("Send stop notification") {
    }
}

def getModel(){
    return env.MODEL;
}

def getModelParams(){
    return env.PARAMS
}